### ISSUE TITLE
'-each' fails on emacs26

### ISSUE THREAD

**Issue by mankoff** [daviderestivo/emacs-config#5]
https://github.com/daviderestivo/emacs-config/blob/a4b8a9cf4300fd72083d3e4deabe8ba2cbce59e3/lisp/org-archive-subtree.el#L27

I'm really happy to have found your improved / working subtree archive function. I upgraded to emacs26 yesterday and it stopped working: 

`ad-Advice-org-archive-subtree: Symbol’s function definition is void: -each`

**Comment by mankoff** [comment]
It seems like `dash` isn't loaded by default when I run the same config with emacs25 or emacs26. This archive code works again if I add a `(require 'dash)`.

**Comment by daviderestivo** [comment]
Hi @mankoff,

I will have a look into it and let you know. Currently I'm using emacs 27.x so I need to rollback to 26.2 and make a test.

Regards,
Davide

**Comment by daviderestivo** [comment]
I will add it ... 

Thanks.

**Comment by daviderestivo** [comment]
Fixed in here: https://github.com/daviderestivo/emacs-config/commit/9c413893b66e8e9d8a1714ab53e85e2a30746ee1
